export const aboutus = `Banca Nevoilor Tale din România este parte a Best Group, instituție financiară internațională de origine europeana care oferă servicii bancare și de management al activelor pentru clienți individuali, companii și instituții din peste 40 de țări din Europa, America de Nord, America Latină, Asia și Australia.

Banca Nevoilor Tale este prima instituție financiară internațională care a deschis o sucursală în România după 1989, în prezent deținând o poziție solidă pe piața locală. S-a lansat in 1994, ca bancă de nișă, de Corporate și Investment Banking, dar s-a dezvoltat într-un ritm susținut, prin creștere organică, iar astăzi este o bancă universală care oferă o paleta completă de produse și servicii tuturor categoriilor de clienți.

BNT România funcționează ca o bancă universală, servind toate categoriile de clienți prin cele trei divizii specializate: Wholesale Banking, Mid Corporate și Retail Banking.

Lucram impreuna. 
Daca vom colabora, vom discuta, ne vom asculta si ne vom ajuta unii pe ceilalti, vom avea rezultate mult mai bune. Astfel vom crea un mediu de buna intelegere, respect si incredere. 

Incurajam diversitatea si, impreuna cu toti colegii, partenerii si clientii nostri vom reusi mult mai mult decat individual.Actionam in mod responsabil. Daca ne asumam responsabilitatea actiunilor noastre, vom face schimbari semnificative. Individual sau in echipa, ne asumam deciziile pe care le luam si suntem responsabili pentru rezultatele muncii noastre. 
Suntem constienti de consecintele actiunilor noastre si suntem membrii responsabili ai societatii, pentru care sustinem afaceri durabile.`;

export const terms = `Pentru a trimite aplicatia catre banca va rugam sa cititi cu atentie Termenii si conditiile de mai jos. Prin completarea prezentei aplicatii sunt de acord în mod expres si neechivoc ca toate datele si informatiile personale (inclusiv cod numeric personal CNP) furnizate catre Banca Nevoilor Tale Sucursala Bucuresti  sa fie utilizate de catre aceasta în vederea contactarii mele de catre angajati/colaboratori ai BNTsi solutionarii prezentei aplicatii.
Inteleg si sunt de acord ca, in conformitate cu legea, BNT este abilitata sa efectueze orice verificari, sa solicite si sa obtina informatii despre subsemnatul de la orice autoritate competente, registru public, arhiva, baza de date electronica sau organism abilitat detinator de astfel de informatii.
Imi exprim in mod expres si neechivoc acordul in vederea prelucrarii de catre BNT si entitatile membre ale BNT Group a datelor mele cu caracter personal, inclusiv cod numeric personal (CNP), (dupa cum este acest termen definit in Legea nr. 677/2001, cu modificarile ulterioare), atat in scopul procesarii prezentei aplicatii, cat si in scopul bunei derulari a relatiei contractuale, cu transmiterea, inclusiv în scopul prelucrarii acestor date, catre terti imputerniciti de catre BNT sa opereze date cu caracter personal în numele sau, institutii si societati ce au drept obiect de activitate colectarea/furnizarea de informatii despre comportamentul persoanelor beneficiare de servicii bancare.
Am luat la cunostinta ca dispun si îmi pot exercita toate drepturile prevazute de Legea nr. 677/2001: dreptul de informare, dreptul de acces la date, dreptul de interventie, dreptul de opozitie, dreptul de a nu fi suspus unei decizii individuale, dreptul de a ma adresa instantei de judecata (Banca este înscrisa in Registrul de evidenta a operatorilor de date cu caracter personal sub nr. 273).
Totodata, inteleg si sunt de acord ca pentru a primi informatii suplimentare cu privire la suma pe care o pot imprumuta, perioada de rambursare, valoarea ratei lunare, etc. este necesar sa ma prezint in BNT Office-ul al carui client sunt sau in orice BNT Office (daca nu sunt client BNT).
Inteleg si sunt de acord ca BNT are dreptul de a refuza acordarea creditului, urmare neprezentarii de catre subsemnatul a tuturor documentelor solicitate (cum ar fi: documente de identitate, doveda venitului/veniturilor obtinute, documente referitoare la garantii) si urmare a verificarilor efectuate de catre BNT, in conformitate cu procedurile interne si dispozitiile legale in vigoare.`;

// variabile cu texte
